import axios from "axios";

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const LOGOUT = 'LOGOUT';
export const GET_BOOKS = 'GET_BOOKS';
export const BOOK_ERROR = 'BOOK_ERROR';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const ENTER_SEARCH = 'ENTER_SEARCH';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const ADD_BOOK = 'ADD_BOOK';
export const DELETE_BOOK ='DELETE_BOOK';
export const GET_BOOK = 'GET_BOOK';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';